import sys
import os
import json

# Ensure the simulation folder is in the path to allow direct running
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

from simulation import Simulation

CACHE_FILE = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "outputs", "gst_cache.json")
DIR_NAMES = ["A", "B", "C", "D"]


def load_from_cache():
    if not os.path.exists(CACHE_FILE):
        return None, None
    with open(CACHE_FILE, 'r') as f:
        data = json.load(f)
    gst_values = data.get("gst_values")
    counts_list = data.get("total_counts_list")
    if gst_values is None or counts_list is None:
        return None, None
    detected_data = {}
    for i, name in enumerate(DIR_NAMES):
        detected_data[name] = counts_list[i] if i < len(counts_list) else {}
    return gst_values, detected_data


def main():
    # Try loading pre-computed GST values from cache (generated by process_all_videos.py)
    gst_values, detected_data = load_from_cache()

    if gst_values is None or detected_data is None:
        print("No cached GST data found. Using fallback example data.")
        # Example fallback data
        detected_data = {
            "A": {"car": 4, "motorcycle": 5},
            "B": {"car": 6, "motorcycle": 10, "truck": 2},
            "C": {"bus": 3, "car": 5},
            "D": {"car": 2, "truck": 1, "motorcycle": 7}
        }
        gst_values = None

    print("Detected vehicle data per approach:")
    for k, v in detected_data.items():
        print(f"  {k}: {v}")
    if gst_values:
        print(f"Pre-computed GST values: {[f'{g:.2f}s' for g in gst_values]}")

    # Initialize and run the high-fidelity traffic simulation
    # Set debug=True if you wish to see the vector fallbacks and lane corridors
    sim = Simulation(detected_data, debug=False, gst_values=gst_values)
    sim.run()


if __name__ == "__main__":
    main()